apiVersion: v1
kind: Pod
metadata:
  name: fishi0x01-debug-alpine
spec:
  containers:
  - image: alpine:3.11
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always
